spring:
  application:
    name: user-service
  cloud: 
    config: 
      override-none: true
    
server:
  port: 8101
  
sp:
  user-service: 
    users: "[{\"id\":7, \"username\":\"熊猫\",\"password\":\"123\"},{\"id\":8, \"username\":\"大象\",\"password\":\"123\"},{\"id\":9, \"username\":\"老虎\",\"password\":\"123\"}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka